### ISSUE TITLE
Problem installing laminar_python

### ISSUE THREAD

**Issue by matmoro1994** [juhuntenburg/laminar_python#11]
Hi!
I tried to install laminar_python in my computer and I did all the steps. I install it in usr/bin and I set the PYTHONPATH. But when I try to do

import laminar_python

in Python, I have this error:

 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "laminar_python/__init__.py", line 3, in <module>
    from .volumetric_layering import create_levelsets, layering,  \
  File "laminar_python/volumetric_layering.py", line 5, in <module>
    import cbstoolsjcc
  File "laminar_python/cbstoolsjcc/__init__.py", line 2, in <module>
    import os, _cbstoolsjcc
ImportError: libjvm.so: cannot open shared object file: No such file or directory

I set also the path for the file libjvm.so but nothing changed.

Any suggestions to solve this problem?
Thank you
Matteo

**Comment by juhuntenburg** [comment]
Hi Matteo, 

you might want to consider instead of laminar_python to use [Nighres](http://nighres.readthedocs.io/en/latest/index.html), which has the same and more functionalities and is being actively developed (in contrast to laminar_python). Both packages, however, are *not* tried and tested for Mac yet. For Nighres you might circumvent the problem using the [Docker image](http://nighres.readthedocs.io/en/latest/installation.html#docker).

That said, if you want to try and make your installation work, the reason for your error is that original code has been compiled against a Java installation that is different from yours. I can give you instructions how it can sometimes be fixed on Linux systems, but I know little about Mac, so I am not sure how that would translate:
1. Find your libjvm.so location
find / -type f -name libjvm.so
2. Add it to the library path. Depending on you Java installation it will be something similar to one of these
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-8-openjdk-amd64/lib/amd64/server/

This can be run within the current terminal for a single session, or made permanent by adding the export statement to your terminal execution script (i.e., .bashrc on most linux systems).

3. If that doesn't do the trick you can  try running::
sudo R CMD javareconf

Hope this helps, let me know!
Julia

**Comment by matmoro1994** [comment]
Hi Julia,

I installed Nighres as you suggest and everything works correctly. I have some questions for you:

- Which atlas is used by default in the brain segmentation?

- Can we use our own atlas for brain tissue labeling, and if yes how to proceed?

Thank you very much

Matteo Moro

**Comment by matmoro1994** [comment]
Hi Julia,

I installed Nighres as you suggest and everything works correctly. I have some questions for you:

- Which atlas is used by default in the brain segmentation function in Nighres?

- Can we use our own atlas for brain tissue labeling, and if yes how to proceed?

Thank you very much!

Bests

Matteo Moro

**Comment by juhuntenburg** [comment]
Hi Matteo, 

sorry for the late reply, could you post this on the Nighres issue tracker?

Thanks! 
Julia
